[book]
authors = ["Jeiwan"]
language = "en"
multilingual = false
src = "src"
title = "Uniswap V3 Development Book"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/Jeiwan/uniswapv3-book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Jeiwan/uniswapv3-book/edit/main/{path}"

[preprocessor.katex]
after = ["links"]