baseURL = 'https://jeiwan.net/uniswapv3-book'
languageCode = 'en-us'
title = 'Uniswap V3 Development Book'
theme = 'hugo-book'

[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.tableOfContents]
startLevel = 1