name: GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.36'

      - name: Install KaTex
        run: cargo install mdbook-katex

      - name: Build
        run: mdbook build --dest-dir public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
